const types = {
  SET_CUSTOMER: '@shop/SET_CUSTOMER',
  REQUEST_PETSHOPS: '@shop/REQUEST_PETSHOPS',
  SET_PETSHOPS: '@shop/SET_PETSHOPS',
  SET_PETSHOP_MAP_SELECTED: '@shop/SET_PETSHOP_MAP_SELECTED' ,
  SET_MAP_CENTER: '@shop/SET_MAP_CENTER',
}

export default types